### ISSUE TITLE
Enter the full user story documentation on the wiki.

### ISSUE THREAD

**Issue by david-fisher** [david-fisher/320-F21-Track-1#11]
Enter the full user story documentation on the wiki. This will be the basis for the track's version of the project. Include both stories an acceptance tests. Include mock ups, where appropriate. Create a top level issue for each story and assign to the appropriate teams.

**Comment by tomking** [comment]
User stories are now available at [this location](https://github.com/david-fisher/320-F21-Track-1/wiki/User-Stories). Teams can open/assign their issues as they see fit.
