### ISSUE TITLE
Merge objects GameObject with state RuleList

### ISSUE THREAD

**Issue by tomking** [david-fisher/320-F21-Track-1#93]

**Comment by tomking** [comment]
Changes to consider to GameObject:

- [ ] Fix method naming (this class also does not follow the conventions that it should)
- [ ] Add method to set entire array of Rules at once

Changes to consider to RuleList:

- [ ] This class should not have an RNG attribute called Score. Remove this and instead include the ability to include RNG for different attributes where it makes sense.

**Comment by imnnos** [comment]
- Never mind we're keeping score.
- Add score to constructors.
- Add getScore() method.
